-- PricePeek baseline schema and reliable price-check scheduling state.
-- Review this migration in a non-production environment before applying it.

create extension if not exists pgcrypto;

create table if not exists public.tracked_products (
  id uuid primary key default gen_random_uuid(),
  device_id text not null,
  amazon_url text not null,
  asin text,
  title text not null,
  image_url text,
  current_price numeric,
  target_price numeric not null,
  last_checked_at timestamptz,
  notification_sent boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.tracked_products
  add column if not exists is_active boolean,
  add column if not exists next_check_at timestamptz,
  add column if not exists consecutive_failures integer,
  add column if not exists last_check_error text;

update public.tracked_products
set
  is_active = coalesce(is_active, true),
  next_check_at = coalesce(next_check_at, last_checked_at, created_at, now()),
  consecutive_failures = coalesce(consecutive_failures, 0),
  notification_sent = coalesce(notification_sent, false);

alter table public.tracked_products
  alter column is_active set default true,
  alter column is_active set not null,
  alter column next_check_at set default now(),
  alter column next_check_at set not null,
  alter column consecutive_failures set default 0,
  alter column consecutive_failures set not null,
  alter column notification_sent set default false,
  alter column notification_sent set not null;

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  tracked_product_id uuid not null references public.tracked_products(id) on delete cascade,
  price numeric not null,
  checked_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  device_id text primary key,
  subscription jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.api_rate_limits (
  identifier text primary key,
  request_count integer not null default 0,
  window_started_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'tracked_products_target_price_positive'
      and conrelid = 'public.tracked_products'::regclass
  ) then
    alter table public.tracked_products
      add constraint tracked_products_target_price_positive
      check (target_price > 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'tracked_products_current_price_nonnegative'
      and conrelid = 'public.tracked_products'::regclass
  ) then
    alter table public.tracked_products
      add constraint tracked_products_current_price_nonnegative
      check (current_price is null or current_price >= 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'tracked_products_failures_nonnegative'
      and conrelid = 'public.tracked_products'::regclass
  ) then
    alter table public.tracked_products
      add constraint tracked_products_failures_nonnegative
      check (consecutive_failures >= 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'price_history_price_nonnegative'
      and conrelid = 'public.price_history'::regclass
  ) then
    alter table public.price_history
      add constraint price_history_price_nonnegative check (price >= 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'api_rate_limits_request_count_nonnegative'
      and conrelid = 'public.api_rate_limits'::regclass
  ) then
    alter table public.api_rate_limits
      add constraint api_rate_limits_request_count_nonnegative
      check (request_count >= 0);
  end if;
end $$;

create index if not exists tracked_products_price_check_queue_idx
  on public.tracked_products (next_check_at, id)
  where is_active = true;

create index if not exists tracked_products_device_created_idx
  on public.tracked_products (device_id, created_at desc);

create index if not exists price_history_product_checked_idx
  on public.price_history (tracked_product_id, checked_at);

-- These uniqueness guarantees are required by the application's upsert calls.
create unique index if not exists push_subscriptions_device_id_uidx
  on public.push_subscriptions (device_id);

create unique index if not exists api_rate_limits_identifier_uidx
  on public.api_rate_limits (identifier);
